

replicaCount: 2

# Following will allow a renaming of all kubauth kubernetes resources
# Allow overriding base name of all resources
baseNameOverride:

# Image may be different for containers
image:
  pullSecrets: []


# -- Annotations to be added to the pod
podAnnotations: {}

# -- Annotations to be added to all other resources
commonAnnotations: {}


# Security Context for each containers
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - "ALL"

# -- Security Context for the whole pod
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault


# NodeSelector for the pod to be installed
nodeSelector: {}

# -- Tolerations for the pod to be installed
tolerations: []

# -- Affinity for the pod to be installed
affinity: {}


# Will default to "kubauth.baseName"
deploymentName:

# Will default to "kubauth.baseName"
serviceAccountName:

# Will default to "kubauth.baseName"
roleName:

networkPolicies:
  # If false, no network policy will be defined at all. For system which does not support them.
  enabled: true
  # NOTE: There will be network policies in some submodule, to allow ingress => service

  # Following are for special cases. Should be false in usual deployment
  # Allow all pods communication in deployment namespace. Also allow pod to resolve name using core dns
  # Set if kubauth modules are spread on several pods
  allowIntraNamespace: false
  # Allow outgoing connection from deployment namespaces
  allowAllEgress: false

  # Default to {{ include "kubauth.baseName" .}}-allow-intra-namespace
  allowIntraNamespacePolicyName:
  # Default to {{ include "kubauth.baseName" .}}-allow-all-egress
  allowAllEgressPolicyName:

oidc:
  enabled: true

  # Allow to change some logger configuration
  logger:
    mode: json  # "Log mode (dev or json)
    level: debug # Log level(DEBUG, INFO, WARN, ERROR)
  # Dump all http server req/resp: 0:No  1:Short info message, 2:full info message, 3:Full json sump
  dumpExchanges: 0
  # Display all command line flags on boot
  displayFlags: true

  # Where to store OidcClient resources.
  clients:
    createNamespace: true
    namespace: kubauth-oidc
    # Default to {{ include "kubauth.baseName" .}}-oidc-client
    roleName:
  issuer: # TBD
  postLogoutURL: # TBD
  server:
    tls: true
    bindAddr: "0.0.0.0"
    bindPort:  8102
    certificateIssuer: # TBD
    issuerKind: ClusterIssuer

    resourcesFolder: resources

    # Default to {{ include "kubauth.baseName" .}}-oidc-server
    certificateName:
    # Default to {{ include "kubauth.baseName" .}}-oidc-server-cert
    certificateSecretName:
    # Default to {{ include "kubauth.baseName" .}}-oidc-server
    serviceName:

  ingress:
    enabled: true
    class: nginx  # Only nginx currently supported
    host: # TBD

  sso:
    createNamespace: true
    namespace: kubauth-sso
    sticky: true
    lifeTime: "8h"
    cleanupPeriod: "5m"
    # Default to {{ include "kubauth.baseName" .}}-oidc-sso
    roleName:

  idp:
    baseURL: http://localhost:8101
    # TODO: Refactor this and add a secret for auth
    rootCAPath: # TBD if https.
    insecureSkipVerify: false

  image:
    repository: quay.io/kubauth/kubauth
    # -- Overrides the image tag whose default is the chart appVersion.
    tag:
    pullPolicy: IfNotPresent

  # The address the probe endpoint binds to.
  healthProbeBindPort: 8111
  disableProbes: false

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  extraEnv:
  additionalArgs: []
  extraVolumes: []
  #   - name:
  #     mountPath:
  #     claimName:
  extraSecrets: []
  #  - name:
  #    mountPath:
  #    secretName:

  # Container specific securityContext
  securityContext:

  metrics:
    enabled: false
    bindPort: 8444
    secured: false  # Set both TLS and client auth (see https://book.kubebuilder.io/reference/metrics)
    # This will be used to validate communication with the metrics endpoint
    # By default, will use a self signed certificate issuer. But, you can provide your own ClusterIssuer
    certificateClusterIssuer:
    serviceMonitor:
      enabled: false
      name:  # -- Will default to {{ include "kubauth.baseName" . }}-oidc

    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-metrics
    serviceName:
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-metrics
    certificateName:
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-metrics
    secretName:
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-metrics
    certificateSelfSignedIssuerName:

  webhooks:
    enabled: true
    port: 9444

    # This will be used to validate communication between the API server and this webhook server
    # By default, will use a self signed certificate issuer. But, you can provide your own ClusterIssuer
    certificateClusterIssuer:

    # Following will allow a renaming of kubauth webhook related kubernetes resources
    # Leave it empty to use default values will works in most cases
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-webhook
    serviceName:
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-webhook
    certificateName:
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-webhook
    secretName:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-oidc-webhook
    certificateSelfSignedIssuerName:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-oidc-validating-webhook-configuration
    validatingWebhookConfiguration:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-oidc-mutating-webhook-configuration
    mutatingWebhookConfiguration:

  # Default to {{ include "kubauth.baseName" .}}-oidc
  ingressName:
  # Default to {{ include "kubauth.baseName" .}}-oidc-ingress
  ingressNetworkPolicyName:
  # Default to {{ include "kubauth.baseName" .}}-oidc-jwt-key
  jwtSigningKeySecretName:
  # Default to {{ include "kubauth.baseName" .}}-oidc-jwt-secret
  jwtSecretRoleName:

userdb:
  enabled: true

  namespace: kubauth-users
  createNamespace: true

  # Allow to change some logger configuration
  logger:
    mode: json  # "Log mode (dev or json)
    level: info # Log level(DEBUG, INFO, WARN, ERROR)
  # Dump all http server req/resp: 0:No  1:Short info message, 2:full info message, 3:Full json sump
  dumpExchanges: 0
  # Display all command line flags on boot
  displayFlags: true

  image:
    repository: quay.io/kubauth/kubauth
    # -- Overrides the image tag whose default is the chart appVersion.
    tag:
    pullPolicy: IfNotPresent

  server:
    tls: false
    bindAddr: "127.0.0.1"
    bindPort:  8101
    certificateIssuer: # TBD
    issuerKind: ClusterIssuer

    # Default to {{ include "kubauth.baseName" .}}-userdb-server
    certificateName:
    # Default to {{ include "kubauth.baseName" .}}-userdb-server-cert
    certificateSecretName:
    # Default to {{ include "kubauth.baseName" .}}-userdb-server
    serviceName:

    service:
      enabled: false

  ingress:
    enabled: false
    class: nginx  # Only nginx currently supported
    host: # TBD

  # The address the probe endpoint binds to.
  healthProbeBindPort: 8112
  disableProbes: false

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  extraEnv:
  additionalArgs: []
  extraVolumes: []
  #   - name:
  #     mountPath:
  #     claimName:
  extraSecrets: []
  #  - name:
  #    mountPath:
  #    secretName:


  # Container specific securityContext
  securityContext:

  metrics:
    enabled: false
    bindPort: 8445
    secured: false  # Set both TLS and client auth (see https://book.kubebuilder.io/reference/metrics)
    # This will be used to validate communication with the metrics endpoint
    # By default, will use a self signed certificate issuer. But, you can provide your own ClusterIssuer
    certificateClusterIssuer:
    serviceMonitor:
      enabled: false
      name:  # -- Will default to {{ include "kubauth.baseName" . }}-userdb

    # -- Will default to {{ include "kubauth.baseName" . }}-userdb-metrics
    serviceName:
    # -- Will default to {{ include "kubauth.baseName" . }}-userdb-metrics
    certificateName:
    # -- Will default to {{ include "kubauth.baseName" . }}-userdb-metrics
    secretName:
    # -- Will default to {{ include "kubauth.baseName" . }}-userdb-metrics
    certificateSelfSignedIssuerName:

  webhooks:
    enabled: true
    port: 9445

    # This will be used to validate communication between the API server and this webhook server
    # By default, will use a self signed certificate issuer. But, you can provide your own ClusterIssuer
    certificateClusterIssuer:

    # Following will allow a renaming of kubauth webhook related kubernetes resources
    # Leave it empty to use default values will works in most cases
    # -- Will default to {{ include "kubauth.baseName" . }}-userdb-webhook
    serviceName:
    # -- Will default to {{ include "kubauth.baseName" . }}-userdb-webhook
    certificateName:
    # -- Will default to {{ include "kubauth.baseName" . }}-userdb-webhook
    secretName:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-userdb-webhook
    certificateSelfSignedIssuerName:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-userdb-validating-webhook-configuration
    validatingWebhookConfiguration:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-userdb-mutating-webhook-configuration
    mutatingWebhookConfiguration:

  # Default to {{ include "kubauth.baseName" .}}-userdb
  ingressName:
  # Default to {{ include "kubauth.baseName" .}}-userdb-ingress
  ingressNetworkPolicyName:




data:
  # Must be false on initial deployment, as webhooks must be ready for data to be deployed
  enabled: false
  userdb:
    enabled: true
    users: []
    #  - login: john
    #    spec:
    #      passwordHash: "$2a$12$iw.ywr.87sGXAkK1HSIU6OIBTyVs4/at1T7I1ueLPPt9CPxOpkmbW"
    #      claims:
    #        job: boss
    #        email: john@thecompany.com
    #      commonNames:
    #        - John THEBOSS
    #      emails:
    #        - john@thecompany.com
    #      comment: The CEO
    #      disabled: false
    groupBindings: []
    #  - user: john
    #    group: managers
    #  - user: john
    #    group: golfPlayers
    groups: []
    #  - name: managers
    #    spec:
    #      claims:
    #        access: full
  oidc:
    enabled: true
    oidcClients: []
    #  - name: example
    #    spec:
    #      id: example-app
    #      hashedSecret: "$2a$12$pxfZs1UOw3y.4IJAOVqG8OIr4n6304Y2QRBefiQpB3AnDGthYF4ba" # // hash of ZXhhbXBsZS1hcHAtc2VjcmV0
    #      redirectURIs:
    #        - "http://example.local/callback"
    #      grantTypes: [ "implicit", "refresh_token", "authorization_code", "password", "client_credentials" ]
    #      responseTypes: ["id_token", "code", "token", "id_token token", "code id_token", "code token", "code id_token token"]
    #      scopes: [ "openid", "offline", "profile", "groups", "email"]


