{{- if .Values.merger.enabled }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubauth.merger.configMapName" . }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    providers:
      {{- range .Values.merger.providers }}
      - name: {{ .name }}
        httpConfig:
          baseURL: {{ .httpConfig.baseUrl }}
        credentialAuthority: {{ .credentialAuthority }}
        groupAuthority: {{ .groupAuthority }}
        groupPattern: "{{ .groupPattern | default "%s" }}"
        claimAuthority: {{ .claimAuthority  }}
        claimPattern: "{{ .claimPattern | default "%s" }}"
        nameAuthority: {{ .nameAuthority }}
        emailAuthority: {{ .emailAuthority  }}
        critical: {{ .critical | default true }}
        uidOffset: {{ .uidOffset | default 0 }}
      {{- end }}

{{- end }}