
{{/*
Expand userdb container
*/}}
{{- define "container.userdb" -}}
- name: userdb
  command:
    - /kubauth
  args:
    - userdb
    - --logMode={{ .Values.userdb.logger.mode }}
    - --logLevel={{ .Values.userdb.logger.level }}
    - --displayFlags={{ .Values.userdb.displayFlags }}
    - --healthProbeBindAddress={{ printf ":%.0f" .Values.userdb.healthProbeBindPort }}
    - --leaderElect=false
    - --enableWebhook={{ .Values.userdb.webhooks.enabled }}
    {{- if .Values.userdb.webhooks.enabled }}
    - --webhookPort={{ .Values.userdb.webhooks.port }}
    - --webhookCertPath=/tmp/k8s-webhooks-server/serving-certs
    - --webhookCertName=tls.crt
    - --webhookCertKey=tls.key
    {{- end }}
    {{- if .Values.userdb.metrics.enabled }}
    - --metricsBindAddress={{ printf ":%.0f" .Values.userdb.metrics.bindPort }}
        {{- if .Values.userdb.metrics.secured }}
    - --metricsSecure=true
    - --metricsCertPath=/tmp/k8s-metrics-server/metrics-certs
        {{- else }}
    - --metricsSecure=false
        {{- end }}
    {{- else }}
    - --metricsBindAddress=0
    {{- end }}
    - --usersNamespace={{ .Values.userdb.namespace }}
    - --tls={{ .Values.userdb.server.tls }}
    - --dumpExchanges={{ .Values.userdb.dumpExchanges }}
    - --bindAddr={{ .Values.userdb.server.bindAddr }}
    - --bindPort={{ .Values.userdb.server.bindPort }}
    - --certDir=/cert/server
    {{-  range .Values.userdb.additionalArgs }}
    - {{ . }}
    {{- end }}
  ports:
    - containerPort: {{ .Values.userdb.server.bindPort }}
      name: userdb
      protocol: TCP
    {{- if .Values.userdb.metrics.enabled }}
    - containerPort: {{ .Values.userdb.metrics.bindPort }}
      name: metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.userdb.webhooks.enabled }}
    - containerPort: {{ .Values.userdb.webhooks.port }}
      name: webhook
      protocol: TCP
    {{- end }}
  {{- if not .Values.userdb.disableProbes }}
  livenessProbe:
    httpGet:
      path: /healthz
      port: {{ .Values.userdb.healthProbeBindPort }}
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /readyz
      port: {{ .Values.userdb.healthProbeBindPort }}
    initialDelaySeconds: 5
    periodSeconds: 10
  {{- end }}
  image: "{{ .Values.userdb.image.repository }}:{{ .Values.userdb.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.userdb.image.pullPolicy }}
  {{- with .Values.userdb.extraEnv }}
  env:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.userdb.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  securityContext:
    {{- toYaml .Values.containerSecurityContext | nindent 4 }}
    {{- with .Values.userdb.securityContext }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  volumeMounts:
    {{- if .Values.userdb.metrics.enabled }}
    - mountPath: /tmp/k8s-metrics-server/metrics-certs
      name: userdb-metrics-certs
      readOnly: true
    {{- end }}
    {{- if .Values.userdb.webhooks.enabled }}
    - mountPath: /tmp/k8s-webhooks-server/serving-certs
      name: userdb-webhooks-certs
      readOnly: true
    {{- end }}
    {{- if .Values.userdb.server.tls }}
    - mountPath: /cert/server
      name: userdb-cert-server
      readOnly: true
    {{- end }}
    {{- range .Values.userdb.extraVolumes }}
    - name: {{ .name }}
      mountPath: {{ .mountPath }}
    {{- end }}
    {{- range .Values.userdb.extraSecrets }}
    - name: {{ .name }}
      mountPath: {{ .mountPath }}
      readOnly: true
    {{- end }}

{{- end }}

{{/*
Expand userdb volumes in pod
*/}}
{{- define "volumes.userdb" -}}
{{- if .Values.userdb.metrics.enabled }}
- name: userdb-metrics-certs
  secret:
    secretName: {{ include "kubauth.userdb.metrics.secretName" . }}
{{- end }}
{{- if .Values.userdb.webhooks.enabled }}
- name: userdb-webhooks-certs
  secret:
    secretName: {{ include "kubauth.userdb.webhooks.secretName" . }}
{{- end }}
{{- if .Values.userdb.server.tls }}
- name: userdb-cert-server
  secret:
    defaultMode: 420
    secretName: {{ include "kubauth.userdb.server.certificateSecretName" . }}
{{- end }}
{{- range .Values.userdb.extraVolumes }}
- name: {{ .name }}
  persistentVolumeClaim:
    claimName: {{ .claimName }}
{{- end }}
{{- range .Values.userdb.extraSecrets }}
- name: {{ .name }}
  secret:
    secretName: {{ .secretName }}
{{- end }}
{{- end }}
