{{- if .Values.userdb.enabled }}

{{- if .Values.userdb.server.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubauth.userdb.server.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 443
      name: userdb
      protocol: TCP
      targetPort: {{ .Values.userdb.server.bindPort }}
  selector:
    {{- include "kubauth.selectorLabels" . | nindent 6 }}
{{- end }}

{{- if .Values.userdb.metrics.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubauth.userdb.metrics.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: https
      port: {{ .Values.userdb.metrics.bindPort }}
      protocol: TCP
      targetPort: {{ .Values.userdb.metrics.bindPort }}
  selector:
    {{- include "kubauth.selectorLabels" . | nindent 6 }}
{{- end }}


{{- if .Values.userdb.webhooks.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubauth.userdb.webhooks.serviceName" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.userdb.webhooks.port }}
  selector:
    {{- include "kubauth.selectorLabels" . | nindent 6 }}

{{- end }}

{{- end }}
