---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubauth.deploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubauth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.podAnnotations .Values.merger.enabled }}
      annotations:
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.merger.enabled }}
        checksum/merger-config: {{ include (print $.Template.BasePath "/merger/configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "kubauth.labels" . | nindent 8 }}
        {{- include "kubauth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.oidc.enabled }}
        {{- include "container.oidc" . | nindent 8 }}
        {{- end }}
        {{- if .Values.logger.enabled }}
        {{- include "container.logger" . | nindent 8 }}
        {{- end }}
        {{- if .Values.merger.enabled }}
        {{- include "container.merger" . | nindent 8 }}
        {{- end }}
        {{- if .Values.ucrd.enabled }}
        {{- include "container.ucrd" . | nindent 8 }}
        {{- end }}
        {{- if .Values.ldap.enabled }}
        {{- include "container.ldap" . | nindent 8 }}
        {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "kubauth.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.oidc.enabled -}}
        {{- include "volumes.oidc" . | nindent 8 }}
        {{- end }}
        {{- if .Values.logger.enabled -}}
        {{- include "volumes.logger" . | nindent 8 }}
        {{- end }}
        {{- if .Values.merger.enabled -}}
        {{- include "volumes.merger" . | nindent 8 }}
        {{- end }}
        {{- if .Values.ucrd.enabled -}}
        {{- include "volumes.ucrd" . | nindent 8 }}
        {{- end }}
        {{- if .Values.ldap.enabled -}}
        {{- include "volumes.ldap" . | nindent 8 }}
        {{- end }}

