{{- if or .Values.oidc.enabled .Values.ucrd.enabled }}

{{- if .Values.networkPolicies.enabled }}

{{- if .Values.networkPolicies.allowAllEgress}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubauth.allowAllEgressPolicyName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}        # selects all pods in the namespace
  policyTypes:
    - Egress
  egress:
    - {}                   # allow to anywhere on any port/protocol

{{- end }}

{{- if .Values.networkPolicies.allowIntraNamespace }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubauth.allowIntraNamespacePolicyName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}  # applies to all pods in the namespace
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}  # allow traffic from all pods in the namespace
  egress:
    - to:
        - podSelector: {}  # allow traffic to all pods in the namespace

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubauth.allowIntraNamespacePolicyName" . }}-dns
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}       # all pods in this namespace
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

{{- end }}
{{- end }}

{{- end }}