---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubauth.kubotal.io
  resources:
  - oidcclients
  - upstreamproviders
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubauth.kubotal.io
  resources:
  - oidcclients/status
  - upstreamproviders/status
  verbs:
  - get
  - patch
  - update
