{{ if .Values.ucrd.enabled }}
{{ if .Values.ucrd.ingress.enabled }}
{{ if  eq .Values.ucrd.ingress.class "nginx" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubauth.ucrd.ingressName" . }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  annotations:
  {{ if .Values.ucrd.server.tls }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  {{ end }}
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ required "ingress.host must be defined!" .Values.ucrd.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "kubauth.ucrd.server.serviceName" . }}
                port:
                  number: 443
            path: /
            pathType: Prefix
{{ else }}
  {{- fail "Unmanaged ingress class" }}
{{ end }}
{{ end }}
{{ end }}
