{{- if .Values.ucrd.enabled }}
{{- if .Values.networkPolicies.enabled }}
{{- if .Values.ucrd.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubauth.ucrd.ingressNetworkPolicyName" .}}
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
    - from:
      {{ if  eq .Values.ucrd.ingress.class "nginx" }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      {{ else }}
        {{- fail "Unmanaged ingress class" }}
      {{ end }}
      ports:
        - port: {{ .Values.ucrd.server.bindPort }}
          protocol: TCP
  podSelector:
    matchLabels:
      {{- include "kubauth.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}
{{- end }}
{{- end }}
