
{{/*
Expand oidc container
*/}}
{{- define "container.oidc" -}}
- name: oidc
  command:
    - /kubauth
  args:
    - oidc
    - --logMode={{ .Values.oidc.logger.mode }}
    - --logLevel={{ .Values.oidc.logger.level }}
    - --displayFlags={{ .Values.oidc.displayFlags }}
    - --healthProbeBindAddress={{ printf ":%.0f" .Values.oidc.healthProbeBindPort }}
    - --leaderElect=false {{/* ne .Values.replicaCount 1.0 */}}
    - --enableWebhook={{ .Values.oidc.webhooks.enabled }}
    {{- if .Values.oidc.webhooks.enabled }}
    - --webhookPort={{ .Values.oidc.webhooks.port }}
    - --webhookCertPath=/tmp/k8s-webhooks-server/serving-certs
    - --webhookCertName=tls.crt
    - --webhookCertKey=tls.key
    {{- end }}
    {{- if .Values.oidc.metrics.enabled }}
    - --metricsBindAddress={{ printf ":%.0f" .Values.oidc.metrics.bindPort }}
        {{- if .Values.oidc.metrics.secured }}
    - --metricsSecure=true
    - --metricsCertPath=/tmp/k8s-metrics-server/metrics-certs
        {{- else }}
    - --metricsSecure=false
        {{- end }}
    {{- else }}
    - --metricsBindAddress=0
    {{- end }}
    - --tls={{ .Values.oidc.server.tls }}
    - --dumpExchanges={{ .Values.oidc.dumpExchanges }}
    - --bindAddr={{ .Values.oidc.server.bindAddr }}
    - --bindPort={{ .Values.oidc.server.bindPort }}
    - --certDir=/cert/server
    - --issuer={{ required "'oidc.issuer' must be defined" .Values.oidc.issuer }}
    - --jwtKeySecretName={{ include "kubauth.oidc.jwtSigningKeySecretName" . }}
    - --jwtKeySecretNamespace={{ .Release.Namespace }}
    - --resources={{ .Values.oidc.server.resourcesFolder }}
    - --postLogoutURL={{ required "'oidc.postLogoutURL' must be defined" .Values.oidc.postLogoutURL }}
    - --ssoNamespace={{ .Values.oidc.sso.sessionNamespace | default .Release.Namespace }}
    - --upstreamNamespace={{ .Values.oidc.upstreamNamespace | default .Release.Namespace }}
    - --stickySso={{ .Values.oidc.sso.sticky }}
    - --ssoLifetime={{ .Values.oidc.sso.lifeTime }}
    - --cleanupPeriod={{ .Values.oidc.sso.cleanupPeriod }}
    - --idProviderBaseURL={{ .Values.oidc.idProvider.baseURL }}
    - --idProviderRootCAPath={{ .Values.oidc.idProvider.rootCAPath }}
    - --idProviderInsecureSkipVerify={{ .Values.oidc.idProvider.insecureSkipVerify }}
    - --allowPasswordGrant={{ .Values.oidc.allowPasswordGrant }}
    - --enforcePKCE={{ .Values.oidc.enforcePKCE }}
    - --jwtAccessToken={{ .Values.oidc.jwtAccessToken }}
    - --clientPrivilegedNamespace={{ .Values.oidc.clientPrivilegedNamespace | default .Release.Namespace }}
    {{-  range .Values.oidc.additionalArgs }}
    - {{ . }}
    {{- end }}
  ports:
    - containerPort: {{ .Values.oidc.server.bindPort }}
      name: oidc
      protocol: TCP
    {{- if .Values.oidc.metrics.enabled }}
    - containerPort: {{ .Values.oidc.metrics.bindPort }}
      name: metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.oidc.webhooks.enabled }}
    - containerPort: {{ .Values.oidc.webhooks.port }}
      name: webhook-oidc
      protocol: TCP
    {{- end }}
  {{- if not .Values.oidc.disableProbes }}
  livenessProbe:
    httpGet:
      path: /healthz
      port: {{ .Values.oidc.healthProbeBindPort }}
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /readyz
      port: {{ .Values.oidc.healthProbeBindPort }}
    initialDelaySeconds: 5
    periodSeconds: 10
  {{- end }}
  image: "{{ .Values.oidc.image.repository }}:{{ .Values.oidc.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.oidc.image.pullPolicy }}
  {{- with .Values.oidc.extraEnv }}
  env:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.oidc.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  securityContext:
    {{- toYaml .Values.containerSecurityContext | nindent 4 }}
    {{- with .Values.oidc.securityContext }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  volumeMounts:
    {{- if .Values.oidc.metrics.enabled }}
    - mountPath: /tmp/k8s-metrics-server/metrics-certs
      name: oidc-metrics-certs
      readOnly: true
    {{- end }}
    {{- if .Values.oidc.webhooks.enabled }}
    - mountPath: /tmp/k8s-webhooks-server/serving-certs
      name: oidc-webhooks-certs
      readOnly: true
    {{- end }}
    {{- if .Values.oidc.server.tls }}
    - mountPath: /cert/server
      name: oidc-cert-server
      readOnly: true
    {{- end }}
    {{- range .Values.oidc.extraVolumes }}
    - name: {{ .name }}
      mountPath: {{ .mountPath }}
    {{- end }}
    {{- range .Values.oidc.extraSecrets }}
    - name: {{ .name }}
      mountPath: {{ .mountPath }}
      readOnly: true
    {{- end }}

{{- end }}

{{/*
Expand oidc volumes in pod
*/}}
{{- define "volumes.oidc" -}}
{{- if .Values.oidc.metrics.enabled }}
- name: oidc-metrics-certs
  secret:
    secretName: {{ include "kubauth.oidc.metrics.secretName" . }}
{{- end }}
{{- if .Values.oidc.webhooks.enabled }}
- name: oidc-webhooks-certs
  secret:
    secretName: {{ include "kubauth.oidc.webhooks.secretName" . }}
{{- end }}
{{- if .Values.oidc.server.tls }}
- name: oidc-cert-server
  secret:
    defaultMode: 420
    secretName: {{ include "kubauth.oidc.server.certificateSecretName" . }}
{{- end }}
{{- range .Values.oidc.extraVolumes }}
- name: {{ .name }}
  persistentVolumeClaim:
    claimName: {{ .claimName }}
{{- end }}
{{- range .Values.oidc.extraSecrets }}
- name: {{ .name }}
  secret:
    secretName: {{ .secretName }}
{{- end }}
{{- end }}
