{{- if .Values.oidc.enabled }}
{{- if .Values.oidc.clients.createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.oidc.clients.namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec: {}
{{- end }}

{{- if .Values.oidc.sso.createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.oidc.sso.namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec: {}
{{- end }}
{{- end }}


