{{- if .Values.oidc.enabled }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubauth.oidc.clientRoleName" . }}
  namespace: {{ .Values.oidc.clients.namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - kubauth.kubotal.io
    resources:
      - oidcclients
    verbs:
      - get
      - list
      - watch


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubauth.serviceAccountName" . }}-{{ include "kubauth.oidc.clientRoleName" . }}
  namespace: {{ .Values.oidc.clients.namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubauth.oidc.clientRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubauth.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}



---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubauth.oidc.ssoRoleName" . }}
  namespace: {{ .Values.oidc.sso.namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - kubauth.kubotal.io
    resources:
      - ssosessions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubauth.serviceAccountName" . }}-{{ include "kubauth.oidc.ssoRoleName" . }}
  namespace: {{ .Values.oidc.sso.namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubauth.oidc.ssoRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubauth.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubauth.oidc.jwtSecretRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubauth.serviceAccountName" . }}-{{ include "kubauth.oidc.jwtSecretRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubauth.oidc.jwtSecretRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubauth.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- end }}

