{{- if .Values.oidc.enabled }}

---
# This ClusterRole to be used in roleBinding to grant oidcClient management permissions.
# Referencing from a RoleBinding (Not a ClusterRoleBinding) limits the scope to the hosting namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubauth.oidc.clientAdminClusterRoleName" . }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - kubauth.kubotal.io
    resources:
      - oidcclients
      - upstreamproviders
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch

---
# This ClusterRole is intended to be used by the kubauth controller.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubauth.oidc.clientControllerClusterRoleName" . }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - kubauth.kubotal.io
    resources:
      - oidcclients
      - upstreamproviders
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - kubauth.kubotal.io
    resources:
      - oidcclients/status
      - upstreamproviders/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubauth.serviceAccountName" . }}-{{ include "kubauth.oidc.clientControllerClusterRoleName" . }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubauth.oidc.clientControllerClusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubauth.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}


---
# This Role is intended to be used by the kubauth controller.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubauth.oidc.ssoRoleName" . }}
  namespace: {{ .Values.oidc.sso.sessionNamespace | default .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - kubauth.kubotal.io
    resources:
      - ssosessions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubauth.serviceAccountName" . }}-{{ include "kubauth.oidc.ssoRoleName" . }}
  namespace: {{ .Values.oidc.sso.sessionNamespace | default .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubauth.oidc.ssoRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubauth.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}


---
# This Role is intended to be used by the kubauth controller.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubauth.oidc.jwtSecretRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
    resourceNames:
      - {{ include "kubauth.oidc.jwtSigningKeySecretName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubauth.serviceAccountName" . }}-{{ include "kubauth.oidc.jwtSecretRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubauth.oidc.jwtSecretRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubauth.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- end }}

