
{{- if .Values.oidc.enabled }}
{{ range .Values.oidc.upstreamProviders }}

{{ $name := .name}}

{{- if .clientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: upstream-{{ $name }}
  namespace: {{ $.Values.oidc.upstreamProvidersNamespace | default $.Release.Namespace }}
type: Opaque
stringData:
  clientSecret: "{{ .clientSecret }}"
{{- end }}


---
apiVersion: kubauth.kubotal.io/v1alpha1
kind: UpstreamProvider
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.oidc.upstreamProvidersNamespace | default $.Release.Namespace }}
spec:
  type: {{ .type }}
  displayName: {{ .displayName }}
  enabled: {{ .enabled }}
  {{ with .clientSpecific }}clientSpecific: {{ . }}{{ end }}
  {{ with .issuerURL }}issuerURL: {{ .}}{{- end }}
  {{- with .certificateAuthority }}
  certificateAuthority:
    {{- with .configMap }}
    configMap:
      name: {{ .name }}
      key: {{ .key }}
    {{- end }}
    {{- with .secret }}
    secret:
      name: {{ .name }}
      key: {{ .key }}
    {{- end }}
  {{- end }}
  {{ with .insecureSkipVerify }}insecureSkipVerify: {{ . }}{{ end }}
  {{ with .redirectURL }}redirectURL: {{ .}}{{ end }}
  {{ with .clientId }}clientId: {{ .}}{{ end }}
  {{- with .clientSecret }}
  clientSecret:
    secret:
      name: upstream-{{ $name }}
      key: clientSecret
  {{- end }}
  {{- with .scopes }}
  scopes:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- with .explicitConfig }}
  explicitConfig:
    {{ with .authorization_endpoint }}authorization_endpoint: {{ .}}{{ end }}
    {{ with .token_endpoint }}token_endpoint: {{ .}}{{ end }}
    {{ with .device_authorization_endpoint }}device_authorization_endpoint: {{ .}}{{ end }}
    {{ with .userinfo_endpoint }}userinfo_endpoint: {{ .}}{{ end }}
    {{ with .jwks_uri }}jwks_uri: {{ .}}{{ end }}
    {{- with .id_token_signing_alg_values_supported }}
    id_token_signing_alg_values_supported:
      {{- range . }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{ with .introspection_endpoint }}introspection_endpoint: {{ .}}{{ end }}
    {{ with .end_session_endpoint }}end_session_endpoint: {{ .}}{{ end }}
  {{- end}}
{{- end }}
{{- end }}