#    Copyright 2025 Kubotal
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

namespaces:
    users: kubauth-users
    oidcClientsDefault: kubauth

users: []
#  - login: john
#    spec:
#      passwordHash: "$2a$12$iw.ywr.87sGXAkK1HSIU6OIBTyVs4/at1T7I1ueLPPt9CPxOpkmbW"
#      claims:
#        job: boss
#        email: john@thecompany.com
#      commonNames:
#        - John THEBOSS
#      emails:
#        - john@thecompany.com
#      comment: The CEO
#      disabled: false

groupBindings: []
#  - user: john
#    group: managers
#  - user: john
#    group: golfPlayers

groups: []
#  - name: managers
#    claims:
#      access: full
#    comment

roleBindings: []
#  - name
#    role:
#    clusterRole
#    namespace:
#    users: []
#    groups: []

clusterRoleBindings: []
#  - name
#    clusterRole:
#    users: []
#    groups: []

oidcClients: []
#  - name: example
#    spec:
#      id: example-app
#      namespace: tenant1 # Used for multiTenant
#      redirectURIs:
#        - "http://example.local/callback"
#      grantTypes: [ "implicit", "refresh_token", "authorization_code", "password", "client_credentials" ]
#      responseTypes: ["id_token", "code", "token", "id_token token", "code id_token", "code token", "code id_token token"]
#      scopes: [ "openid", "offline", "profile", "groups", "email"]
#      secrets:
#        - name: oidcSecret1
#          key: secret
#          hashed: false
#          value: inout5feg   # If "", then  it is assumed the secret exists.
#        - name: oidcSecret2
#          key: secret
#          hashed: true
#          value: 1973VRShk370ps2b0FJsjeD5rJG3JOWYZMKIX.gGidagWcAX4EiLO   # Result of `kc hash inout5feg`





# -- Annotations to be added to all other resources
commonAnnotations: {}
