{{- if .Values.ucrd.enabled }}
{{- if .Values.ucrd.createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.ucrd.namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec: {}
{{- end }}
{{- end }}


