


# Some notes about network policies in a KIND cluster:
#
# These are experimental result.
#
# - KIND version:  kind v0.31.0-fip.1-alpha.27+13313e9c6d8843
# - K8S version: 1.34.0
# - Network: docker.io/kindest/kindnetd:v20250512-df8de77b
#
# A netPol (kubauth-oidc-ingress) to allow ingress to access kubauth is required in all case
#
# About connection from api server to kubauth webhooks:
#
# - No need to set a netPol on a single node cluster.
# - On a multi node cluster:
#   - need to activate networkPolicies for webhooks (networkPolicies.forWebhooks: true)
#   - need to define ipBlock for these policies  (networkPolicies.ipBlock: 172.XX.0.0/16)
#
# NB: If deployInControlPlane: true, it may work on some try: if the kubauth pod is on the same node as the api server,
#



#ports:
#  oidc: 6801
#  ucrd: 6802
#  ldap: 6803
#  merger: 6804
#  audit: 6805

# Hard coded to one for now.
# Unpredictable result for more than one instance.
# replicaCount: 1

# Following will allow a renaming of all kubauth kubernetes resources
# Allow overriding base name of all resources
baseNameOverride:

# Other image: properties are defined by container.
image:
  pullSecrets: []

# Setup toleration and node selector to run inside control plane
deployInControlPlane: true

# -- Annotations to be added to the pod
podAnnotations: {}

# -- Annotations to be added to all other resources
commonAnnotations: {}


# Security Context for each containers
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - "ALL"

# -- Security Context for the whole pod
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault


# NodeSelector for the pod to be installed
nodeSelector: {}

# -- Tolerations for the pod to be installed
tolerations: []

# -- Affinity for the pod to be installed
affinity: {}


# Will default to "kubauth.baseName"
deploymentName:

# Will default to "kubauth.baseName"
serviceAccountName:

# Will default to "kubauth.baseName"
roleName:

networkPolicies:
  # If false, no network policy will be defined at all. For system which does not support them.
  enabled: true
  # NOTE: There will be network policies in some submodule, to allow ingress => service

  # Specific switch to no set apiServer -> webhooks one.
  forWebhooks: true

  # If set, this will be included in ingress[0].from[X].ipBlock for webhooks related netpol
  # Set to the node CIDR. May be required for multinode KIND cluster.
  # (KIND networkPolicies implementation seems unstable).
  ipBlock:



  # *** WARNING Not yet implemented. (4 variables) ***
  # Following are for special cases. Should be false in usual deployment
  # Allow all pods communication in deployment namespace. Also allow pod to resolve name using core dns
  # Set if kubauth modules are spread on several pods
  allowIntraNamespace: false
  # Allow outgoing connection from deployment namespaces
  allowAllEgress: false

  # Default to {{ include "kubauth.baseName" .}}-allow-intra-namespace
  allowIntraNamespacePolicyName:
  # Default to {{ include "kubauth.baseName" .}}-allow-all-egress
  allowAllEgressPolicyName:



oidc:
  enabled: true

  issuer: # TBD
  postLogoutURL: # TBD
  # https://www.scottbrady.io/oauth/why-the-resource-owner-password-credentials-grant-type-is-not-authentication-nor-suitable-for-modern-applications
  allowPasswordGrant: false   # Allow Resource Owner Password Credentials (ROPC) grant type, aka the password grant.
  enforcePKCE: false  # If set, all authorization code grand must use PKCE

  idp:
    baseURL: http://localhost:6805
    rootCAPath: # TBD if https.
    insecureSkipVerify: false

  # Allow to change some logger configuration
  logger:
    mode: json  # "Log mode (dev or json)
    level: info # Log level(DEBUG, INFO, WARN, ERROR)
  # Dump all http server req/resp: 0:No  1:Short info message, 2:full info message, 3:Full json sump
  dumpExchanges: 0
  # Display all command line flags on boot
  displayFlags: true

  # Where to store OidcClient resources.
  clients:
    createNamespace: true
    namespace: kubauth-oidc
    # Default to {{ include "kubauth.baseName" .}}-oidc-client
    roleName:

  server:
    tls: true
    bindAddr: "0.0.0.0"
    bindPort: 6801    # See internal/global/default.go
    certificateIssuer: # TBD
    issuerKind: ClusterIssuer

    resourcesFolder: resources

    # Default to {{ include "kubauth.baseName" .}}-oidc-server
    certificateName:
    # Default to {{ include "kubauth.baseName" .}}-oidc-server-cert
    certificateSecretName:
    # Default to {{ include "kubauth.baseName" .}}-oidc-server
    serviceName:

  ingress:
    enabled: true
    class: nginx  # Only nginx currently supported
    host: # TBD

  sso:
    createNamespace: true
    namespace: kubauth-sso
    sticky: true
    lifeTime: "8h"
    cleanupPeriod: "5m"
    # Default to {{ include "kubauth.baseName" .}}-oidc-sso
    roleName:

  image:
    repository: quay.io/kubauth/exec/kubauth-server
    # -- Overrides the image tag whose default is the chart appVersion.
    tag:
    pullPolicy: IfNotPresent

  # The address the probe endpoint binds to.
  healthProbeBindPort: 8110
  disableProbes: false

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  extraEnv:
  additionalArgs: []
  extraVolumes: []
  #   - name:
  #     mountPath:
  #     claimName:
  extraSecrets: []
  #  - name:
  #    mountPath:
  #    secretName:

  # Container specific securityContext
  securityContext:

  metrics:
    enabled: false
    bindPort: 8443
    secured: false  # Set both TLS and client auth (see https://book.kubebuilder.io/reference/metrics)
    # This will be used to validate communication with the metrics endpoint
    # By default, will use a self signed certificate issuer. But, you can provide your own ClusterIssuer
    certificateClusterIssuer:
    serviceMonitor:
      enabled: false
      name:  # -- Will default to {{ include "kubauth.baseName" . }}-oidc

    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-metrics
    serviceName:
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-metrics
    certificateName:
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-metrics
    secretName:
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-metrics
    certificateSelfSignedIssuerName:

  webhooks:
    enabled: true
    port: 9443

    # This will be used to validate communication between the API server and this webhook server
    # By default, will use a self signed certificate issuer. But, you can provide your own ClusterIssuer
    certificateClusterIssuer:

    # Following will allow a renaming of kubauth webhook related kubernetes resources
    # Leave it empty to use default values will works in most cases
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-webhook
    serviceName:
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-webhook
    certificateName:
    # -- Will default to {{ include "kubauth.baseName" . }}-oidc-webhook
    secretName:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-oidc-webhook
    certificateSelfSignedIssuerName:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-oidc-validating-webhook-configuration
    validatingWebhookConfiguration:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-oidc-mutating-webhook-configuration
    mutatingWebhookConfiguration:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-oidc-webhook
    networkPolicyName:


  # Default to {{ include "kubauth.baseName" .}}-oidc
  ingressName:
  # Default to {{ include "kubauth.baseName" .}}-oidc-ingress
  ingressNetworkPolicyName:
  # Default to {{ include "kubauth.baseName" .}}-oidc-jwt-key
  jwtSigningKeySecretName:
  # Default to {{ include "kubauth.baseName" .}}-oidc-jwt-secret
  jwtSecretRoleName:

audit:
  enabled: true

  namespace: kubauth-audit
  createNamespace: true

  idp:
    baseURL: http://localhost:6802
    rootCAPath: # TBD if https.
    insecureSkipVerify: false

  cleaner:
    loginLifetime: "8h"
    cleanupPeriod: "5m"

  # Allow to change some logger configuration
  logger:
    mode: json  # "Log mode (dev or json)
    level: info # Log level(DEBUG, INFO, WARN, ERROR)
  # Dump all http server req/resp: 0:No  1:Short info message, 2:full info message, 3:Full json sump
  dumpExchanges: 0
  # Display all command line flags on boot
  displayFlags: true

  image:
    repository: quay.io/kubauth/exec/kubauth-server
    # -- Overrides the image tag whose default is the chart appVersion.
    tag:
    pullPolicy: IfNotPresent

  server:
    tls: false
    bindAddr: "127.0.0.1"
    bindPort:  6805
    certificateIssuer: # TBD
    issuerKind: ClusterIssuer
    bfaProtection: false

    # Default to {{ include "kubauth.baseName" .}}-audit-server
    certificateName:
    # Default to {{ include "kubauth.baseName" .}}-audit-server-cert
    certificateSecretName:


  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  extraEnv:
  additionalArgs: []
  extraVolumes: []
  #   - name:
  #     mountPath:
  #     claimName:
  extraSecrets: []
  #  - name:
  #    mountPath:
  #    secretName:

  # Container specific securityContext
  securityContext:

merger:
  enabled: false

  # Allow to change some logger configuration
  logger:
    mode: json  # "Log mode (dev or json)
    level: info # Log level(DEBUG, INFO, WARN, ERROR)
  # Dump all http server req/resp: 0:No  1:Short info message, 2:full info message, 3:Full json sump
  dumpExchanges: 0
  # Display all command line flags on boot
  displayFlags: true

  image:
    repository: quay.io/kubauth/exec/kubauth-server
    # -- Overrides the image tag whose default is the chart appVersion.
    tag:
    pullPolicy: IfNotPresent

  providers:
    - name: ucrd
      httpConfig:
        baseUrl: http://localhost:6802
      credentialAuthority: true
      groupAuthority: true
      groupPattern: "%s"
      claimAuthority: true
      claimPattern: "%s"
      nameAuthority: true
      emailAuthority: true
      critical: true
      uidOffset: 0

  server:
    tls: false
    bindAddr: "127.0.0.1"
    bindPort:  6804
    certificateIssuer: # TBD
    issuerKind: ClusterIssuer
    bfaProtection: false

    # Default to {{ include "kubauth.baseName" .}}-merger-server
    certificateName:
    # Default to {{ include "kubauth.baseName" .}}-logger-server-cert
    certificateSecretName:

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  extraEnv:
  additionalArgs: []
  extraVolumes: []
  #   - name:
  #     mountPath:
  #     claimName:
  extraSecrets: []
  #  - name:
  #    mountPath:
  #    secretName:

  # Container specific securityContext
  securityContext:

  configMapName:

ldap:
  enabled: false

  ldap:
    # The host and port of the LDAP server.
    host:
    #  If port isn't supplied, it will be guessed based on the TLS configuration. (389 or 636).
    port:

    # Timeout on connection to ldap server. Default to 10
    timeoutSec:
    # Required if LDAP host does not use TLS.
    insecureNoSSL:
    # Don't verify the CA.
    insecureSkipVerify:
    # Connect to the insecure port then issue a StartTLS command to negotiate a
    # secure connection. If unsupplied secure connections will use the LDAPS protocol.
    startTLS:

    # Only one of rootCaData, rootCaPath or rootCaSecret must be defined
    # Path to a trusted root certificate file.
    rootCaPath:
    # Base64 encoded PEM data containing root CAs.
    rootCaData:
    # A secret hosting the CA, as base64 encoded value, at the 'rootCaSecretPath' location.
    # The secret can be generated using trust-manager from cert-manager
    rootCaSecret:
    rootCaSecretPath:  # Default to 'ca.crt'

    # Path to a client cert file. If LDAP server require a certificate based client authentication
    clientCert:
    # Path to a client private key file. If LDAP server require a certificate based client authentication
    clientKey:

    # BindDN and BindPW for an application service account. The connector uses these
    # credentials to search for users and groups.
    bindDN:
    bindPW:

    groupSearch:
      # BaseDN to start the search from. For example "cn=groups,dc=example,dc=com"
      baseDN:
      # Optional filter to apply when searching the directory. For example "(objectClass=posixGroup)"
      filter:
      # The filter for group/user relationship will be: (<linkGroupAttr>=<Value of LinkUserAttr for the user>)
      # If there is several value for LinkUserAttr, we will loop on.
      linkGroupAttr:
      linkUserAttr:
      # The attribute of the group that represents its name.
      nameAttr:
      # Defaults to "sub"
      scope:
    userSearch:
      # BaseDN to start the search from. For example "cn=users,dc=example,dc=com"
      baseDN:
      #  Optional filter to apply when searching the directory. For example "(objectClass=person)"
      filter:
      # Attribute to match against the login. This will be translated and combined with the other filter as "(<loginAttr>=<login>)".
      loginAttr:
      # Can either be:
      #	  "sub" - search the whole sub tree
      #	  "one" - only search one level
      scope:
      # The attribute providing the numerical user ID
      numericalIdAttr:
      # The attribute providing the user's email
      emailAttr:
      # The attribute providing the user's common name
      cnAttr:

# Here is a sample configuration for an openldap server
#    host: openldap-main.openldap.svc
#    insecureNoSSL: false
#    #rootCaData: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FUR...........UlRJRklDQVRFLS0tLS0K"
#    #rootCaPath: ./ca.crt
#    #rootCaSecret: certs-bundle
#    bindDN: cn=admin,dc=odp,dc=com
#    bindPW: myPassword
#    groupSearch:
#      baseDN: ou=Groups,dc=odp,dc=com
#      filter: (objectClass=posixgroup)
#      linkGroupAttr: memberUid
#      linkUserAttr: uid
#      nameAttr: cn
#    timeoutSec: 10
#    userSearch:
#      baseDN: ou=Users,dc=odp,dc=com
#      cnAttr: cn
#      emailAttr: mail
#      filter: (objectClass=inetOrgPerson)
#      loginAttr: uid
#      numericalIdAttr: uidNumber

  # Allow to change some logger configuration
  logger:
    mode: json  # "Log mode (dev or json)
    level: info # Log level(DEBUG, INFO, WARN, ERROR)
  # Dump all http server req/resp: 0:No  1:Short info message, 2:full info message, 3:Full json sump
  dumpExchanges: 0
  # Display all command line flags on boot
  displayFlags: true

  image:
    repository: quay.io/kubauth/exec/kubauth-server
    # -- Overrides the image tag whose default is the chart appVersion.
    tag:
    pullPolicy: IfNotPresent

  server:
    tls: false
    bindAddr: "127.0.0.1"
    bindPort:  6803
    certificateIssuer: # TBD
    issuerKind: ClusterIssuer
    bfaProtection: false

    # Default to {{ include "kubauth.baseName" .}}-ldap-server
    certificateName:
    # Default to {{ include "kubauth.baseName" .}}-ldap-server-cert
    certificateSecretName:

  # Default to {{ include "kubauth.baseName" .}}-ldap-ca-secret
  caSecretRoleName:

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  extraEnv:
  additionalArgs: []
  extraVolumes: []
  #   - name:
  #     mountPath:
  #     claimName:
  extraSecrets: []
  #  - name:
  #    mountPath:
  #    secretName:

  # Container specific securityContext
  securityContext:

  configMapName:

ucrd:
  enabled: true

  namespace: kubauth-users
  createNamespace: true

  # Allow to change some logger configuration
  logger:
    mode: json  # "Log mode (dev or json)
    level: info # Log level(DEBUG, INFO, WARN, ERROR)
  # Dump all http server req/resp: 0:No  1:Short info message, 2:full info message, 3:Full json sump
  dumpExchanges: 0
  # Display all command line flags on boot
  displayFlags: true

  image:
    repository: quay.io/kubauth/exec/kubauth-server
    # -- Overrides the image tag whose default is the chart appVersion.
    tag:
    pullPolicy: IfNotPresent

  server:
    tls: false
    bindAddr: "127.0.0.1"
    bindPort:  6802
    certificateIssuer: # TBD
    issuerKind: ClusterIssuer
    bfaProtection: false

    # Default to {{ include "kubauth.baseName" .}}-ucrd-server
    certificateName:
    # Default to {{ include "kubauth.baseName" .}}-ucrd-server-cert
    certificateSecretName:

  # The address the probe endpoint binds to.
  healthProbeBindPort: 8111
  disableProbes: false

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  extraEnv:
  additionalArgs: []
  extraVolumes: []
  #   - name:
  #     mountPath:
  #     claimName:
  extraSecrets: []
  #  - name:
  #    mountPath:
  #    secretName:


  # Container specific securityContext
  securityContext:

  metrics:
    enabled: false
    bindPort: 8444
    secured: false  # Set both TLS and client auth (see https://book.kubebuilder.io/reference/metrics)
    # This will be used to validate communication with the metrics endpoint
    # By default, will use a self signed certificate issuer. But, you can provide your own ClusterIssuer
    certificateClusterIssuer:
    serviceMonitor:
      enabled: false
      name:  # -- Will default to {{ include "kubauth.baseName" . }}-ucrd

    # -- Will default to {{ include "kubauth.baseName" . }}-ucrd-metrics
    serviceName:
    # -- Will default to {{ include "kubauth.baseName" . }}-ucrd-metrics
    certificateName:
    # -- Will default to {{ include "kubauth.baseName" . }}-ucrd-metrics
    secretName:
    # -- Will default to {{ include "kubauth.baseName" . }}-ucrd-metrics
    certificateSelfSignedIssuerName:

  webhooks:
    enabled: true
    port: 9444

    # This will be used to validate communication between the API server and this webhook server
    # By default, will use a self signed certificate issuer. But, you can provide your own ClusterIssuer
    certificateClusterIssuer:

    # Following will allow a renaming of kubauth webhook related kubernetes resources
    # Leave it empty to use default values will works in most cases
    # -- Will default to {{ include "kubauth.baseName" . }}-ucrd-webhook
    serviceName:
    # -- Will default to {{ include "kubauth.baseName" . }}-ucrd-webhook
    certificateName:
    # -- Will default to {{ include "kubauth.baseName" . }}-ucrd-webhook
    secretName:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-ucrd-webhook
    certificateSelfSignedIssuerName:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-ucrd-validating-webhook-configuration
    validatingWebhookConfiguration:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-ucrd-mutating-webhook-configuration
    mutatingWebhookConfiguration:
    # -- Will default to {{ include "kubauth.webhook.baseName" . }}-ucrd-webhook
    networkPolicyName:

  # Default to {{ include "kubauth.baseName" .}}-ucrd
  ingressName:
  # Default to {{ include "kubauth.baseName" .}}-ucrd-ingress
  ingressNetworkPolicyName:

  adminRoleName:
  systemRoleName:

