{{- range .Values.oidcClients }}
---
apiVersion: kubauth.kubotal.io/v1alpha1
kind: OidcClient
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespaces.kubauth.oidcClients }}
spec:
  {{- with .hashedSecret }}
  hashedSecret: "{{ . }}"
  {{- end }}
  {{- with .redirectURIs }}
  redirectURIs:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- with .grantTypes }}
  grantTypes:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- with .responseTypes }}
  responseTypes:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- with .scopes }}
  scopes:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- with .public}}
  public: {{ . }}
  {{- end }}
  {{- with .audiences }}
  audiences:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- with .forceOpenIdScope }}
  forceOpenIdScope: {{ . }}
  {{- end }}
  {{- with .postLogoutURL }}
  postLogoutURL: {{ . }}
  {{- end }}
  {{- with .displayName }}
  displayName: {{ . }}
  {{- end }}
  {{- with .description }}
  description: {{ . }}
  {{- end }}
  {{- with .entryURL }}
  entryURL: {{ . }}
  {{- end }}
  {{- with .accessTokenLifespan }}
  accessTokenLifespan: {{ . }}
  {{- end }}
  {{- with .refreshTokenLifespan }}
  refreshTokenLifespan: {{ . }}
  {{- end }}
  {{- with .idTokenLifespan }}
  idTokenLifespan: {{ . }}
  {{- end }}



{{- end }}
