
{{/*
Expand logger container
*/}}
{{- define "container.logger" -}}
- name: logger
  command:
    - /kubauth
  args:
    - logger
    - --logMode={{ .Values.logger.logger.mode }}
    - --logLevel={{ .Values.logger.logger.level }}
    - --displayFlags={{ .Values.logger.displayFlags }}
    - --namespace={{ .Values.logger.namespace }}
    - --tls={{ .Values.logger.server.tls }}
    - --dumpExchanges={{ .Values.logger.dumpExchanges }}
    - --bindAddr={{ .Values.logger.server.bindAddr }}
    - --bindPort={{ .Values.logger.server.bindPort }}
    - --certDir=/cert/server
    - --idpBaseURL={{ .Values.logger.idp.baseURL }}
    - --idpRootCAPath={{ .Values.logger.idp.rootCAPath }}
    - --idpInsecureSkipVerify={{ .Values.logger.idp.insecureSkipVerify }}
    - --loginLifetime={{ .Values.logger.cleaner.loginLifetime }}
    - --cleanupPeriod={{ .Values.logger.cleaner.cleanupPeriod }}
    {{-  range .Values.logger.additionalArgs }}
    - {{ . }}
    {{- end }}
  ports:
    - containerPort: {{ .Values.logger.server.bindPort }}
      name: logger
      protocol: TCP
  image: "{{ .Values.logger.image.repository }}:{{ .Values.logger.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.logger.image.pullPolicy }}
  {{- with .Values.logger.extraEnv }}
  env:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.logger.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  securityContext:
    {{- toYaml .Values.containerSecurityContext | nindent 4 }}
    {{- with .Values.logger.securityContext }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  volumeMounts:
    {{- if .Values.logger.server.tls }}
    - mountPath: /cert/server
      name: logger-cert-server
      readOnly: true
    {{- end }}
    {{- range .Values.logger.extraVolumes }}
    - name: {{ .name }}
      mountPath: {{ .mountPath }}
    {{- end }}
    {{- range .Values.logger.extraSecrets }}
    - name: {{ .name }}
      mountPath: {{ .mountPath }}
      readOnly: true
    {{- end }}

{{- end }}

{{/*
Expand logger volumes in pod
*/}}
{{- define "volumes.logger" -}}
{{- if .Values.logger.server.tls }}
- name: logger-cert-server
  secret:
    defaultMode: 420
    secretName: {{ include "kubauth.logger.server.certificateSecretName" . }}
{{- end }}
{{- range .Values.logger.extraVolumes }}
- name: {{ .name }}
  persistentVolumeClaim:
    claimName: {{ .claimName }}
{{- end }}
{{- range .Values.logger.extraSecrets }}
- name: {{ .name }}
  secret:
    secretName: {{ .secretName }}
{{- end }}
{{- end }}
