{{- if .Values.logger.enabled }}

{{- if .Values.logger.server.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubauth.logger.server.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubauth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 443
      name: logger
      protocol: TCP
      targetPort: {{ .Values.logger.server.bindPort }}
  selector:
    {{- include "kubauth.selectorLabels" . | nindent 6 }}
{{- end }}

{{- end }}
